### ISSUE TITLE
Login not working anymore..

### ISSUE THREAD

**Issue by yvan-sraka** [simplonco/ATS-SPC-A#21]
Issue replicated on @ELmardi2 configuration!

**Comment by yvan-sraka** [comment]
Did you fix it?

**Comment by solomongamid** [comment]
`$sql = "SELECT * FROM users WHERE passcode = '$mypassword' and name = '$myusername' and # session != CURDATE()";` 
Parce que tu n'as pas de colonne qui s'appelle SESSION dans ta table users, si tu l'ajoutes ça va marcher :wink:!
